version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app_db
    ports:
      - 5432:5432
    
  redis:
    image: redis:latest
    ports:
      - 6379:6379